FROM node:18

ARG UNAME=grendel
ARG UID=999
ARG GID=999

WORKDIR /usr/src/app

# Add grendel user for socket bind
RUN groupadd -g $GID $UNAME
RUN useradd -u $UID -g $GID $UNAME
RUN usermod -aG $UNAME node

USER node

CMD ["npm", "run", "dev"]